package com.termux.terminal;

/**
 * Native methods for creating and managing pseudoterminal subprocesses. C code is in jni/termux.c.
 */
final class JNI {

    static {
        System.loadLibrary("termux");
    }

    /**
     * Create a subprocess. Differs from {@link ProcessBuilder} in that a pseudoterminal is used to communicate with the
     * subprocess.
     * <p/>
     * Callers are responsible for calling {@link #close(int)} on the returned file descriptor.
     *
     * @param cmd       The command to execute
     * @param cwd       The current working directory for the executed command
     * @param args      An array of arguments to the command
     * @param envVars   An array of strings of the form "VAR=value" to be added to the environment of the process
     * @param processId A one-element array to which the process ID of the started process will be written.
     * @return the file descriptor resulting from opening /dev/ptmx master device. The sub process will have opened the
     * slave device counterpart (/dev/pts/$N) and have it as stdint, stdout and stderr.
     */
    public static native int createSubprocess(String cmd, String cwd, String[] args, String[] envVars, int[] processId, int rows, int columns, int cellWidth, int cellHeight);

    /** Set the window size for a given pty, which allows connected programs to learn how large their screen is. */
    public static native void setPtyWindowSize(int fd, int rows, int cols, int cellWidth, int cellHeight);

    /**
     * Causes the calling thread to wait for the process associated with the receiver to finish executing.
     *
     * @return if >= 0, the exit status of the process. If < 0, the signal causing the process to stop negated.
     */
    public static native int waitFor(int processId);

    /** Close a file descriptor through the close(2) system call. */
    public static native void close(int fileDescriptor);

    /** Returns whether libghostty-vt can be loaded by the native bridge. */
    public static native boolean ghosttyIsAvailable();

    /** Create a libghostty-vt terminal context. */
    public static native long ghosttyCreate(int columns, int rows, int maxScrollback, int cellWidthPixels, int cellHeightPixels);

    /** Free a libghostty-vt terminal context. */
    public static native void ghosttyFree(long context);

    /** Resize a libghostty-vt terminal context. */
    public static native void ghosttyResize(long context, int columns, int rows, int cellWidthPixels, int cellHeightPixels);

    /** Write raw VT bytes to a libghostty-vt terminal context. */
    public static native void ghosttyWrite(long context, byte[] data, int offset, int count);

    /** Drain data that libghostty-vt generated for the PTY while processing input or resize effects. */
    public static native byte[] ghosttyDrainPendingPtyWrite(long context);

    /** Consume pending BEL events generated by libghostty-vt effects. */
    public static native int ghosttyConsumeBellCount(long context);

    /** Consume a pending title-changed event generated by libghostty-vt effects. */
    public static native boolean ghosttyConsumeTitleChanged(long context);

    /** Scroll the libghostty-vt terminal viewport. */
    public static native void ghosttyScrollViewport(long context, int tag, int deltaRows);

    /** Reset a libghostty-vt terminal context. */
    public static native void ghosttyReset(long context);

    /** Read an integer-like field from a libghostty-vt terminal context. */
    public static native int ghosttyGetInt(long context, int dataKind);

    /** Read a boolean-like field from a libghostty-vt terminal context. */
    public static native boolean ghosttyGetBoolean(long context, int dataKind);

    /** Read a mode from a libghostty-vt terminal context. */
    public static native boolean ghosttyGetMode(long context, int mode);

    /** Read the terminal title as raw UTF-8 bytes (decode with StandardCharsets.UTF_8), or null when unset. */
    public static native byte[] ghosttyGetTitle(long context);

    /** Read the shell-reported working directory (OSC 7) as raw UTF-8 bytes, or null when unset. */
    public static native byte[] ghosttyGetPwd(long context);

    /** Read scrollbar state as [totalRows, viewportOffset, viewportRows]. */
    public static native int[] ghosttyGetScrollbar(long context);

    /** Snapshot active-screen codepoints and resolved style data from a libghostty-vt render state. */
    public static native int[] ghosttySnapshotCells(long context, int columns, int rows);

    /** Snapshot multi-codepoint render-state graphemes; null entries use the codepoint cell stream. */
    public static native String[] ghosttySnapshotCellText(long context, int columns, int rows);

    /** Mark the latest libghostty-vt render-state snapshot as consumed after GPU rendering succeeds. */
    public static native void ghosttyClearRenderDirtyState(long context);

    /** Snapshot visible Kitty graphics placements and image data from libghostty-vt. */
    public static native Object[] ghosttySnapshotKittyGraphicsPlacements(long context);

    /** Snapshot render-state cursor metadata as [hasValue, x, y, style, visible, wideTail, blinking, passwordInput]. */
    public static native int[] ghosttySnapshotCursor(long context);

    /** Snapshot render-state palette, default foreground/background, and cursor colors. */
    public static native int[] ghosttySnapshotColors(long context);

    /** Apply Termux's default color scheme to a libghostty-vt terminal context. */
    public static native boolean ghosttyApplyDefaultColors(long context, int[] colors);

    /** Encode an Android key event through Ghostty's terminal-aware key encoder. */
    public static native byte[] ghosttyEncodeKey(long context, int keyCode, int keyMod);

    /** Encode a Unicode code point through Ghostty's terminal-aware key encoder. */
    public static native byte[] ghosttyEncodeCodePoint(long context, int codePoint, boolean controlDown, boolean altDown);

    /** Encode a terminal mouse event through Ghostty's terminal-aware mouse encoder. */
    public static native byte[] ghosttyEncodeMouse(long context, int mouseButton, int column, int row, boolean pressed,
                                                   int columns, int rows, int cellWidthPixels, int cellHeightPixels);

    /** Encode a focus in/out event through Ghostty's focus encoder. */
    public static native byte[] ghosttyEncodeFocus(boolean focused);

    /** Encode paste data through Ghostty's terminal-aware paste encoder. */
    public static native byte[] ghosttyEncodePaste(long context, byte[] data);

    /** Format a Ghostty screen-coordinate selection as UTF-8 plain text. */
    public static native byte[] ghosttyFormatSelection(long context, int x1, int y1, int x2, int y2,
                                                       boolean unwrap, boolean trim);

    /** Set or clear the active Ghostty selection using screen-coordinate cells. */
    public static native boolean ghosttySetSelection(long context, int x1, int y1, int x2, int y2, boolean active);

    /** Select and format the Ghostty word at a screen-coordinate cell. */
    public static native byte[] ghosttySelectWord(long context, int x, int y);

    /** Select the Ghostty word at a screen-coordinate cell and return [x1, y1, x2, y2]. */
    public static native int[] ghosttySelectWordBounds(long context, int x, int y);

    /** Return the OSC 8 hyperlink URI at a screen-coordinate cell, or an empty byte array. */
    public static native byte[] ghosttyGetHyperlinkAtLocation(long context, int x, int y);

    /**
     * Scan the whole grid (scrollback + viewport) for OSC 8 hyperlinks in a single JNI crossing and
     * return every discovered URI newline-separated as one UTF-8 byte array. Empty when none.
     */
    public static native byte[] ghosttyGetHyperlinks(long context);

}
